version: '2'
services:
  server:
    image: ffwd/blog:latest
    command: startweb
    depends_on:
      - mongo
      - redis
      - mysql
    ports:
      - "7788:80"
    environment:
      REDIS_HOST: "redis"
      MONGO_URL: "mongodb://mongo:27017"
      MYSQL_HOST: "mysql"
      MYSQL_DATABASE: "ffdata"
      MYSQL_ROOT_PASSWORD: "passwd"
  redis:
    image: redis:4.0-alpine
  mongo:
    image: mongo:3.5
    # volumes:
    #   - /opt/postgres-data:/var/lib/postgresql/data
  mysql:
    image: mysql:5.7.19
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"
      MYSQL_DATABASE: "ffdata"
    volumes:
      - /data/mysql:/var/lib/mysql
